export const CATALOG = {
  WOMAN: [
    "VIEW ALL",
    "THE NEW",
    "GIFTS",
    "BEST SELLERS FOR HER",
    "COATS",
    "PUFFERS & QUILTED",
    "JACKET",
    "KNITWEAR",
    "BLAZERS",
    "WAISTCOATS",
    "DRESSES",
    "SHIRTS",
    "TROUSERS",
    "JEANS",
    "SKIRTS & BERMUDAS",
    "TOPS",
    "T-SHIRTS",
    "SWEATSHIRTS & HOODIES",
    "CARDIGANS & JUMPERS",
    "CO-ORD SETS",
    "SHOES",
    "BAGS",
    "JEWELRY & ACCESSORIES",
    "LINGERIE",
    "PERFUMES",
    "MAKEUP",
  ],

  MAN: [
    "VIEW ALL",
    "PARTY",
    "GIFTS",
    "BEST SELLERS FOR HIM",
    "PUFFERS & GILETS",
    "COATS & TRENCH COATS",
    "JACKETS",
    "SWEATERS & CARDIGANS",
    "HOODIES & SWEATSHIRTS",
    "LEATHER",
    "JEANS",
    "TROUSERS",
    "OVERSHIRTS",
    "QUARTER-ZIP",
    "SHIRTS",
    "TRACKSUITS",
    "SUITS & BLAZERS",
    "POLO SHIRTS",
    "BOOTS",
    "SHOES",
    "BAGS & BACKPACKS",
    "JEWELRY & ACCESSORIES",
    "PERFUMES",
  ],

  KIDS: [
    "VIEW ALL",
    "THE NEW",
    "GIFTS",
    "BABY",
    "GIRLS",
    "BOYS",
    "YEAR 0-4",
    "YEAR 4-8",
    "YEAR 8-12",
    "YEAR 12-16",
    "ACCESSORIES",
  ],

  "PLUSH HOME": [
    "VIEW ALL",
    "NEW IN",
    "GIFTS",
    "BEDDING",
    "BATHROOM",
    "DECOR",
    "KIDS ROOM",
    "OUTDOOR",
    "LIVING ROOM",
    "KITCHENWARE",
    "CANDLES & DIFFUSERS",
  ],

  "50TH ANNIVERSARY": [
    "LIMITED EDITION",
    "ARCHIVE REPLICA",
    "ART TOYS",
    "APPAREL & ACCESSORIES",
    "DESIGNER COLLABS",
    "COLLECTIBLES",
  ],

  "PLUSH BEAUTY": [
    "VIEW ALL",
    "SKINCARE",
    "MAKEUP",
    "FRAGRANCE",
    "HAIRCARE",
    "SETS & GIFTS",
  ],

  "TRAVEL MODE": [
    "LUGGAGE",
    "BACKPACKS",
    "TRAVEL ACCESSORIES",
    "PACKING CUBES",
    "COMFORT WEAR",
    "TOILETRY BAGS",
  ],
} as const;

export type CatalogKey = keyof typeof CATALOG;
